Repository flowacademyhu/cloud-git, pull requests merged in 2022-02, with the labels that each got.

#5 Adding extra files
  prime-numbers.py
  queens-problem.py
Labels: bug

#12 my commit message - first file
  newFile.txt
Labels: bug

#9 Adding new txt file
  nagy01.txt
Labels: documentation

#13 hozzáadtam egy új fájlt
  zuber.txt
Labels: enhancement

#10 new file created
  erdei.txt
Labels: help wanted

#7 Adding my new file
  panakt
Labels: enhancement
